### PR TITLE
add __len__ to Message class that returns len of (clean_)content

### PR DESCRIPTION
**Pull request by Z1R343L**
## Summary

 See commit name

## Checklist

- [x] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by m1raynee** [comment]
`len` function can take exactly one argument. You didn't test the code before making pr, did you?

**Comment by Hunter2807** [comment]
Instead u can split the message content and return the number of words. That would be better **and** useful imho

**Comment by Z1R343L** [comment]
> `len` function can take exactly one argument. You didn't test the code before making pr, did you?

I did Test it and confirm it works

**Comment by Z1R343L** [comment]
> Instead u can split the message content and return the number of words. That would be better **and** useful imho

that wouldnt reflect what ppl expect From a len method

**Comment by m1raynee** [comment]
> > `len` function can take exactly one argument. You didn't test the code before making pr, did you?
> 
> I did Test it and confirm it works

then tell me what i did wrong
```py
>>> class Test:
...     def __init__(self, text):
...         self.text = text
...     def __len__(self, kwarg=True):
...         if kwarg:
...             return len(self.text)
...         else:
...             return len(self.text*2)
... 
>>> test = Test('test')
>>> 
>>> print(len(test))
4
>>> print(len(test, False))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: len() takes exactly one argument (2 given)
```

**Comment by Hunter2807** [comment]
Ah, well you should see the Discord Server. Instead of using the len() function, he wants to call the `.__len__()` method on the Message directly

**Comment by m1raynee** [comment]
then it's just useless

**Comment by Z1R343L** [comment]
> then it's just useless

Possibly feel free to Close

**Review by EQUENOS — CHANGES_REQUESTED** [review]
`__len__` should only take one arg
Also, I don't think it's necessary to create a new variable and return the length, you can just do
```python
def __len__(self):
    return len(self.content)
```

**Pull request closed without merging**
